### ISSUE TITLE
Command '['ninja', '-v', '-j', '1']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by colynhn** [NVIDIA/TransformerEngine#1008]
Building wheel error during installation，Because of the 535 driver requirement, I used the pytorch:22.12-py3 docker, but found that the transformer-engine version was too low, so I upgraded it inside the docker. 
# The upgrade command is as follows:

git clone --branch stable --recursive https://github.com/NVIDIA/TransformerEngine.git
cd TransformerEngine
export NVTE_FRAMEWORK=pytorch   # Optionally set framework
pip install .                   # Build and install

# Environments:

CUDA driver version: 535.161.08
CUDA version: V11.8.89
Pytorch version: 1.14.0a0+410ce96
g++ version: Ubuntu 9.4.0-1ubuntu1~20.04.1)
ninja version: 1.10.0

# The full log is in the '20240710.log' file.
[20240710.log](https://github.com/user-attachments/files/16162754/20240710.log)

This problem has troubled me for a long time. I don't know whether it is an environmental problem or a problem with the underlying dependencies. Please help me solve it. In addition, can the 535 cuda driver use the docker of PyTorch Release 24.02? I don't know if the picture below can be used as a reference：
<img width="941" alt="11111111" src="https://github.com/NVIDIA/TransformerEngine/assets/27861805/25bf111a-5945-4caf-a786-77be2a913ab3">

**Comment by timmoon10** [comment]
Can you try updating your PyTorch version? We have seen similar build failures with PyTorch 2.0.1 (see https://github.com/NVIDIA/TransformerEngine/issues/857#issuecomment-2123099109), so I'm not surprised to have problems with PyTorch 1.14.

[The 535 CUDA driver should support up to CUDA 12.2](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html), so it would be worth trying the 23.09 container (e.g. `nvcr.io/nvidia/pytorch:23.09-py3`)?

**Comment by colynhn** [comment]
@timmoon10 Thanks so much, i will try and feedback soon.
