### ISSUE TITLE
How to use context parallelism with cuDNN

### ISSUE THREAD

**Issue by gudiandian** [NVIDIA/TransformerEngine#1051]
I am using `DotProductAttention` in PyTorch for context parallel with an input shape (q/k/v) of [48, 16534, 18, 128] and the qkv_format is 'bshd', dtype is bf16. 
```
num_heads = q.shape[2]
head_dim = q.shape[3]
core_attn = DotProductAttention(num_heads,
                                            head_dim, 
                                            num_gqa_groups=num_heads, 
                                            attention_dropout=dropout_p,
                                            qkv_format="bshd",
                                            window_size=(-1,-1),
                                            attn_mask_type="no_mask",
                                            )
sp_group = get_sequence_parallel_group()
core_attn.set_context_parallel_group(sp_group, dist.get_process_group_ranks(sp_group), torch.cuda.Stream())
x_mm = core_attn(
                    q, k, v,
                    core_attention_bias_type="no_bias",
                    core_attention_bias=None,
                    cu_seqlens_q=None,
                    cu_seqlens_kv=None
            )
```

When I set the environmental variable to `NVTE_FUSED_ATTN=1, NVTE_FLASH_ATTN=0`, I encounter the following error: 
```
AssertionError: Context parallelism is only implemented with Flash Attention and Fused Attention!
```
When I dig into the problem, I see that the `fused_attention_backend` of attention.py  line 5097 is NoBackend:
```
fused_attention_backend = tex.get_fused_attn_backend(
                    q_type, # DType.kBFloat16
                    kv_type, # DType.kBFloat16
                    QKVLayout[qkv_layout], #NVTE_QKV_Layout.NVTE_BSHD_BSHD_BSHD
                    AttnBiasType[fu_core_attention_bias_type], #NVTE_Bias_Type.NVTE_NO_BIAS
                    AttnMaskType[attn_mask_type], #NVTE_Mask_Type.NVTE_NO_MASK
                    self.attention_dropout, # 0.0
                    query_layer.shape[-2],  # num_attn_heads=18
                    key_layer.shape[-2],  # num_gqa_groups=18
                    max_seqlen_q, # 296
                    max_seqlen_kv, # 296
                    query_layer.shape[-1],  # head_dim=128
                )
```
When I unset the environmental variable `NVTE_FLASH_ATTN`, there is no error but Flash Attention is used, not Fused Attention with cuDNN. 

The GPU device I use is NVIDIA A100, with CUDA 12.2. I installed TransformerEngine by building and installing from source with commit id 0b303dad4c66693351dda93e11c7b61b873751b0. cuDNN version is 8.9.7, flash-attn version is 2.5.8.

I wonder how can I use cuDNN for context parallelism? I would really appreciate any help.

**Comment by yaox12** [comment]
Look into the `get_fused_attn_backend` method and find that for cuDNN version < 9.0.0, seq length should be divisible by 64. https://github.com/NVIDIA/TransformerEngine/blob/0b303dad4c66693351dda93e11c7b61b873751b0/transformer_engine/common/fused_attn/fused_attn.cpp#L128
That's why `fused_attention_backend` returns `NoBackend` I think.

You can upgrade cuDNN to versions greater than 9.0.0 and have a try, but I don't expect any performance improvement from cuDNN fused attention over Flash Attention on A100 (SM80).

**Comment by gudiandian** [comment]
> Look into the `get_fused_attn_backend` method and find that for cuDNN version < 9.0.0, seq length should be divisible by 64.
> 
> https://github.com/NVIDIA/TransformerEngine/blob/0b303dad4c66693351dda93e11c7b61b873751b0/transformer_engine/common/fused_attn/fused_attn.cpp#L128
> 
> 
> For your case, `s = 16534` and `s % 64 = 258`. That's why `fused_attention_backend` returns `NoBackend` I think.
> You can upgrade cuDNN to versions greater than 9.0.0 and have a try, but I don't expect any performance improvement from cuDNN fused attention over Flash Attention on A100 (SM80).

Thank you so much for your reply!
