### ISSUE TITLE
[PyTorch] `logging.basicConfig()` in global scope

### ISSUE THREAD

**Issue by Marks101** [NVIDIA/TransformerEngine#1065]
Hello transformer-engine team,

#889 introduced a logging mechanism, which we really appreciate. But now there are multiple calls to `logging.basicConfig()` in the global/import scope ([here](https://github.com/NVIDIA/TransformerEngine/blame/c8c05f38b773d7509c43dbdbb52cddf58aac6962/transformer_engine/pytorch/attention.py#L102)). I think it makes more sense to call `logging.basicConfig()` on an application level inside a main function and not in a library in global scope.

For example in our training code we call `logging.basicConfig()` in the main function and this now overrides the settings done by transformer-engine. This means that the setup based on the environmental variables `NVTE_DEBUG` and `NVTE_DEBUG_LEVEL` gets overriden as well. We had to explicitly suppress the logging with `logging.getLogger("DotProductAttention").setLevel(logging.WARNING)` in our application code because of the huge amount of log messages by transformer-engine.

A possible solution is to remove the `logging.basicConfig()` from global scope and instead set the log level of each individual logger based on the corresponding environment variables.

Happy to discuss about this 😄

**Comment by cyanguwa** [comment]
Hi @Marks101 , could you please try PR 1074 see if it achieves the expected effect in your application? Thanks.

**Comment by cyanguwa** [comment]
See PR #1074.
