### ISSUE TITLE
If you fail to build wheels on compiling c++, try this.

### ISSUE THREAD

**Issue by lihe50hz** [NVIDIA/TransformerEngine#1084]
1. Find this `TransformerEngine/transformer_engine/pytorch/csrc/userbuffers/userbuffers.cu`.
2. Change all `half` in this file to `TransformerEngine_half` or some other string you like which won't be used that often.

The error comes from `#define te_half nv_bfloat16` at `line 12` in the file.

**Comment by timmoon10** [comment]
This hack shouldn't be necessary with TE 1.9 or newer: https://github.com/NVIDIA/TransformerEngine/pull/949
