### ISSUE TITLE
How to use head dimension 256?

### ISSUE THREAD

**Issue by vedantroy** [NVIDIA/TransformerEngine#1115]
Flash attention benchmarks seem to indicate that CuDNN supports head dimension of 256:
![image](https://github.com/user-attachments/assets/4db910db-43ab-40ec-a5f4-908b365b9415)

I am using the fused attention backend by setting:
```
os.environ["NVTE_FUSED_ATTN"] = "1"
os.environ["NVTE_FUSED_ATTN_FORCE_WORKSPACE_OPT"] = "1"
```

but when I set head dim to 256, I get the following error:
```
RuntimeError: /home/ved/TransformerEngine/transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu:639 in function operator(): cuDNN Error: Num hidden_dim shoud be less than 128 and hidden_dim should be multiple of 8. For more information, enable cuDNN error logging by setting CUDNN_LOGERR_DBG=1 and CUDNN_LOGDEST_DBG=stderr in the environment.
```

Is there anyway to use head dim 256?

**Comment by cyanguwa** [comment]
@vedantroy , cuDNN only support `head_dim = 256` for forward at the moment, not backward.
