### ISSUE TITLE
Transformer Engine using FlashAttention V3

### ISSUE THREAD

**Issue by heavyrain-lzy** [NVIDIA/TransformerEngine#1125]
I find that TE don't support FA-V3. There some error when I use `flash_attn==2.6.3` and `transformer_engine=1.9.0` enable `context parallel` in `Megatron-LM`. Do you have the plan to support it?

**Comment by yaox12** [comment]
FA3 support is added in https://github.com/NVIDIA/TransformerEngine/pull/1019.

**Comment by cyanguwa** [comment]
The context parallel support with FA3 is added in #1232. Please give it a try and let us know if there's any problems.
