### ISSUE TITLE
Question about the  cublaslt_gemm.cu

### ISSUE THREAD

**Issue by south-ocean** [NVIDIA/TransformerEngine#1152]
In the cublas_gemm function of the transformer_engine/common/gemm/cublaslt_gemm.cu file, I see that CUBLALLT is called, but I have a question, that is, if it is pure GEMM, that is, there is no bias or activation behind GEMM, then does it make sense to use CUBLALT in the BLAS function? In my opinion, the upper limit of cublaslt performance is cublas under pure gemm call, so why not take cublas in non-fusion mode and cublaslt in fusion mode?

![Image](https://github.com/user-attachments/assets/b9992304-f073-4492-b59f-6864ac653f82)

![Image](https://github.com/user-attachments/assets/cddcfdaf-027a-42a0-a17d-81b58fdfd0c5)

**Comment by yaox12** [comment]
1. Only cuBLASLt supports FP8 GEMM.
2. For pure GEMMs, cuBLAS calls cuBLASLt internally, so I think there's no difference in terms of performance, while cuBLASLt offers more controls.

**Comment by south-ocean** [comment]
Thanks for the answer, but I still have a little doubt about the second point, you mentioned For pure GEMMs, cuBLAS calls cuBLASLt internally, so I think there's no difference in terms of performance, while cuBLASLt offers more controls. 
1、 In my opinion, cublas calls blaslt for programming convenience, right?  and Doesn't CUBLAS call blaslt cause performance degradation? 
2、As mentioned above, the upper limit of performance for pure GEM CUBLalt should be BLAS, and now all the operators in CUBLAS follow the implementation of CUBLASLT?

**Comment by yaox12** [comment]
Why do you think calling cublaslt will result in performance degradation?
