### ISSUE TITLE
Importing torch gives ImportError - undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by zimmerrol** [NVIDIA/TransformerEngine#1192]
I'm using the latest `nvcr.io/nvidia/pytorch` docker image (i.e., `24.08-py3`) on a machine with an H100 using singularity. The available CUDA version is 12.3 and the driver version is 545.23.08. I cannot import `torch` from `transformer_engine` due to an `ImportError`:

```
ImportError: /usr/local/lib/python3.10/dist-packages/transformer_engine/transformer_engine_torch.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

I didn't install another `torch` version or install/update any package but just the docker image as provided. I get the same issue with any of the 24.XX versions of the docker container. Am I overlooking something, is this an issue with singularity or is `transformer_engine` in the 24.XX version of the `nvcr.io/nvidia/pytorch` docker images broken?

**Comment by photomz** [comment]
Have same issue, what was your fix?
