### ISSUE TITLE
Passing nonexistent argument when flash_attn version is >= 2.5.7

### ISSUE THREAD

**Issue by MaciejBalaNV** [NVIDIA/TransformerEngine#1213]
In [this](https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/attention.py#L5016) place in TE we pass "block_table" argument to either `flash_attn_func` or `flash_attn_varlen_func` functions from `flash_attn` package. However, this function doesn't have this argument, only `flash_attn_varlen_func` function does, as we can verify [here](https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/flash_attn_interface.py#L1102). I'm attaching HEAD of main as a link, but it's the same in version 2.5.8. It results in an error when `flash_attn_func` is chosen.

**Comment by MaciejBalaNV** [comment]
Seems like this bug was added in [this](https://github.com/NVIDIA/TransformerEngine/commit/901e5d2b335878aa11f81dab5ddb12fbfad4322a) commit, which introduced support for FA3.

**Comment by cyanguwa** [comment]
@MaciejBalaNV , thanks for raising this issue. Please try #1222 and let us know if there's still any issues. Thanks!
