### ISSUE TITLE
ImportError in cuda 12

### ISSUE THREAD

**Issue by wplf** [NVIDIA/TransformerEngine#1283]
Hi, ImportError happened when I import TE.
```
 File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/__init__.py", line 29, in _load_library
    solib = importlib.util.module_from_spec(spec)
ImportError: /usr/local/lib/python3.10/dist-packages/transformer_engine/transformer_engine_torch.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN5torch7LibraryC1ENS0_4KindESsSt8optionalIN3c1011DispatchKeyEEPKcj
```

The environ is  
- torch `2.3.0a0+40ec155e58.nv24.03`
- cuda 12.4
- cudnn 90000

I have found this symbol in https://github.com/vllm-project/vllm/issues/5501. 
This symbol is defined in  libtorch_cpu.so https://github.com/vllm-project/vllm/issues/5501#issuecomment-2167338928

Could you help me with this? Thanks.

**Comment by wplf** [comment]
Thank you very much. I've got the source of bug. 

To clarify, the test machine is `cuda 12.4, torch=2.3.0`. And in the beginning, torch is from nvcr:23.10, which is 2.3.0, build TE is built on another machine `cuda 12.1, torch=2.2.2`, and got this bug.

I've tried to build TE from source, but got another bug `cicc is not found`. 
I've checkout that `cicc` is in the folder of `nvvm` in cuda and tried to add the folder of `cicc` into `$PATH`, but still got `cicc` is not found. Do you have any suggestion for this?

**Comment by timmoon10** [comment]
Strange that you need to go into the CUDA internals. Can you try setting `CUDA_PATH` in your environment? Here's a list of common problems when building TE: https://github.com/NVIDIA/TransformerEngine/issues/355#issuecomment-2394353816.

**Comment by wplf** [comment]
CUDA and cicc is both in my path, I guess this is the machine's problem. 
Thank you very much

**Comment by wplf** [comment]
Hi, thank you very much.
I build TE from source in the exactly same environment. This problem disappears. 

Thanks you, again.
