### ISSUE TITLE
`intra_domain_ranks` is not defined in one of the execution paths.

### ISSUE THREAD

**Issue by erhoo82** [NVIDIA/TransformerEngine#1306]
`intra_domain_ranks` at https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/module/base.py#L257C68-L257C86 is not defined when `if num_domains > 1`.

**Comment by denera** [comment]
Thanks! This was internally reported earlier today as well and PR #1305 should fix it.
