### ISSUE TITLE
Build failure, missing cudnn-frontend

### ISSUE THREAD

**Issue by yhtang** [NVIDIA/TransformerEngine#171]
When building from the head of `main`, the [following error occurred](https://github.com/NVIDIA/JAX-Toolbox/actions/runs/4790658021/jobs/8520075783):
```
/opt/transformer-engine/transformer_engine/common/fused_attn/utils.h:11:10: fatal error: cudnn_frontend.h: No such file or directory
#8 455.6            11 | #include <cudnn_frontend.h>
```
It appears that the [cudnn-frontend](https://github.com/NVIDIA/cudnn-frontend) package is needed, but the installation guide does not specify how this dependency should be installed. Could this info be added to the docs?

**Comment by ksivaman** [comment]
What command are you using to install? @yhtang 
In case you're installing locally from source, you would need to run `git submodule init; git submodule update` inside `TransformerEngine` repository.

**Comment by yhtang** [comment]
Thanks for the info. I'll try it now.

**Comment by yhtang** [comment]
It works! Thank you very much!

**Comment by yhtang** [comment]
Updating [this guide](https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/installation.html) with the submodule information could be very helpful for people who would like to install TE in development mode.

**Comment by ksivaman** [comment]
https://github.com/NVIDIA/TransformerEngine/pull/172 @yhtang
