### ISSUE TITLE
Document how to generates the documentation

### ISSUE THREAD

**Issue by nouiz** [NVIDIA/TransformerEngine#177]
Document how to generates the documentation.
This will help when we modify it, to be sure it is well generated.

**Comment by ptrendx** [comment]
The CI generates it using https://github.com/NVIDIA/TransformerEngine/blob/main/.github/workflows/docs.yml - if you submit the PR you can download the zipped version of the built documentation (as an example see https://github.com/NVIDIA/TransformerEngine/actions/runs/4805734879?pr=169)

**Comment by nouiz** [comment]
That should be added in the doc.
Any idea where it should be added in the doc?

Also, could we update the actions to add a comment in the PR with the link to the doc when it is generated? It would make it more accessible.

**Comment by nouiz** [comment]
The zip file link is good.
