### ISSUE TITLE
What's the differences between TransformerEngine and FasterTransformer ?

### ISSUE THREAD

**Issue by butterluo** [NVIDIA/TransformerEngine#263]
What's the differences between TransformerEngine and FasterTransformer ? Are they play the same rule in NVIDIA's strategy road map ?

**Comment by sbhavani** [comment]
FasterTransformer is a set of scripts and kernels to **accelerate inference** for specific model architectures in PyTorch and TensorFlow.

Transformer Engine is a product to accelerate training of Transformer models across frameworks (PyT, JAX, PaddlePaddle, TF) with FP8 as well as custom kernels for all datatypes (e.g. FP16/BF16). Transformer Engine is more modular and has wider model support than FasterTransformer with a focus on training.

**Comment by butterluo** [comment]
> FasterTransformer is a set of scripts and kernels to **accelerate inference** for specific model architectures in PyTorch and TensorFlow.
> 
> Transformer Engine is a product to accelerate training of Transformer models across frameworks (PyT, JAX, PaddlePaddle, TF) with FP8 as well as custom kernels for all datatypes (e.g. FP16/BF16). Transformer Engine is more modular and has wider model support than FasterTransformer with a focus on training.

So FasterTransformer is only for inference? And TransformerEngine is only for training?

**Comment by sbhavani** [comment]
[TensorRT-LLM](https://developer.nvidia.com/blog/nvidia-tensorrt-llm-supercharges-large-language-model-inference-on-nvidia-h100-gpus) was just announced. This will be the accelerated inference solution for LLMs.

With Transformer Engine, you can still do in-framework inference but it won't be an optimized inference solution.

**Comment by aslisabanci** [comment]
@sbhavani Where can we find the TensorrRT-LLM documentation? Even though I'm in the NVIDIA developer program, I couldn't find any information about it except for the blog post you linked. Thanks in advance!

**Comment by sbhavani** [comment]
@aslisabanci TRT-LLM is released now: https://github.com/NVIDIA/TensorRT-LLM
