### ISSUE TITLE
`use_flash_attention` should be set to False when `core_attention_bias` is not None

### ISSUE THREAD

**Issue by yaox12** [NVIDIA/TransformerEngine#340]
IIUC, the current use of flash attention in TE doesn't support attention bias.
https://github.com/NVIDIA/TransformerEngine/blob/06d5fa9749d2ed1e850d14545c90153301a6f542/transformer_engine/pytorch/attention.py#L924-L930
So when `core_attention_bias` is not None, `use_flash_attention` should be set to False to use other backends.

**Comment by ptrendx** [comment]
@cyanguwa could you take a look?

**Comment by cyanguwa** [comment]
Sure, I'll be covering this in #PR [344](https://github.com/NVIDIA/TransformerEngine/pull/344).

**Comment by yaox12** [comment]
Close this issue since it has been resolved in PR #344 .
