### ISSUE TITLE
Project status (TE and FT), regarding inference projects 

### ISSUE THREAD

**Issue by vadimkantorov** [NVIDIA/TransformerEngine#384]
I've noticed that there are no commits in FT since July and very few replies in issues.

Is TransformerEngine the successor of FasterTransformer? Is FT development now paused?

Should TransformerEngine be used for any new inference projects (over FT)? Is TE suitable for A100 / int8 ops?

Thank you!

**Comment by yaox12** [comment]
> Is TransformerEngine the successor of FasterTransformer?

Not exactly. FT is inference-only while TE focuses more on training.

> Is FT development now paused?

Yes.

> Should TransformerEngine be used for any new inference projects (over FT)?

A new inference library will be released from Nvidia at the end of this month.

> Is TE suitable for A100 / int8 ops?

A100 doesn't support FP8, but it can still benefit from other features like kernel fusion from TE. As for int8, I think the answer is no.

**Comment by sbhavani** [comment]
Hi Vadim, [TensorRT-LLM](https://developer.nvidia.com/blog/nvidia-tensorrt-llm-supercharges-large-language-model-inference-on-nvidia-h100-gpus) was just announced. This will be the best inference solution.

With TE, you can still do in framework inference and use it on A100 but it it's not meant for INT8 and not an optimized inference solution.

**Comment by vadimkantorov** [comment]
Great news :) I also hope that more of FT kernels can find way to upstream PyTorch with more time :)
