### ISSUE TITLE
Add llama support to `LayerNormMLP`

### ISSUE THREAD

**Issue by yongyanrao** [NVIDIA/TransformerEngine#408]
I was wondering if there is a plan to add support to llama in `LayerNormMLP`, as there are three linear layers in llama's mlp: https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L220, while other models have only two linear layers.

**Comment by yongyanrao** [comment]
Is it already included by using `swiglu` activation?

**Comment by tangjiangling** [comment]
> I was wondering if there is a plan to add support to llama in LayerNormMLP

+1

**Comment by tangjiangling** [comment]
> Is it already included by using swiglu activation?

That's true.

**Comment by ptrendx** [comment]
That is correct - you can get the llama configuration by setting `normalization` to `RMSNorm` and `activation` to `swiglu`. We fuse the 2 Linear layers in swiglu into a single Linear that creates 2x bigger output. [Here](https://github.com/NVIDIA/TransformerEngine/blob/main/tests/pytorch/test_numerics.py#L393-L428) is a reference pyTorch implementation for comparison.

**Comment by yongyanrao** [comment]
Thank you, @ptrendx
