### ISSUE TITLE
Not enough engineers from NVIDIA?

### ISSUE THREAD

**Issue by PiotrDabkowski** [NVIDIA/TransformerEngine#418]
Dear NVIDIA, H100 costs 30k, why did you put just ~5 engineers on this project? TE is one of the big selling points of H100, yet this library is barely usable.
There is a ton of good PRs stuck as drafts.

**Comment by dunky11** [comment]
Agree, this is hard to use in its current state.

**Comment by nouiz** [comment]
Thanks for your interest in TE. We are actively hiring for this projects, so if you know good candidate, please tell them about our position!

We have already people that use TE, so it is already useful. But I understand that it doesn't fit your need well.
Can you tell us why you find it hard to use?
What makes it not usable for your use case?

We also accept external contribution.

**Comment by nouiz** [comment]
Closing as no reply.
Please open specific issue about he issue you have. We want to support more use cases.
