### ISSUE TITLE
Attention inconsistency between TE and HF

### ISSUE THREAD

**Issue by yongyanrao** [NVIDIA/TransformerEngine#432]
Dear team, we noticed an inconsistency between TE's and HF's implementations of attention.

Let us consider llama model.
- According to HF's llama implementation (https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L421), input layernorm is forced. To match this, we used `input_layernorm=True` in TE.
- We train llama with `num_gqa_groups != num_attention_heads`.
- So in TE, the training leads us to https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/attention.py#L1702 (we used `attention_type="self"`), where the input of `self.key_value` is `hidden_states` before layernorm.
- However, in HF's implementation, https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L424, i.e., the input of attention projections is `hidden_states` after layernorm.

This inconsistency would cause discrepancy. Could you please take a look at it? Thank you in advance.

**Comment by yongyanrao** [comment]
Hi @cyanguwa, Thank you so much for the response. Looking forward to the PR merge.

**Comment by cyanguwa** [comment]
@yongyanrao #434 is merged. Please let me know if there's still any issues. Thanks!

**Comment by cyanguwa** [comment]
Closing the ticket for now. Please reopen it or file another one if the issue persists. Thanks!
