### ISSUE TITLE
TP vs LayerNorm (RMSNorm)

### ISSUE THREAD

**Issue by 152334H** [NVIDIA/TransformerEngine#441]
Quick question: is it normal that the `layer_norm_weights` of a LayerNormLinear / LayerNormMLP / MultiHeadAttention are different across different TP ranks (but identical for the same DP rank across a DP group) after an optimizer step?

My understanding is that the layer norm weights in transformerengine are designed to be duplicated and shared across all ranks.

(I can provide a minimum reproducible example if needed)

**Comment by ptrendx** [comment]
I don't think that's expected so yes, please provide a repro for that. @ksivaman for visibility.

**Comment by 152334H** [comment]
# Core observation
After running forward-backward on a TransformerLayer, and conducting an optimizer.step(), the `layer_norm_weights` in different TP ranks diverge from each other.

```yaml
# before any optimizer.step()
self_attention.layernorm_qkv.weight: False             # expected to be different as TP is TP sharded 
self_attention.layernorm_qkv.layer_norm_weight: True   # expected to be same as LN is supposed to be redundantly duplicated
layernorm_mlp.layer_norm_weight: True

# after optimizer.step()
self_attention.layernorm_qkv.weight: False
self_attention.layernorm_qkv.layer_norm_weight: False  # suddenly different
layernorm_mlp.layer_norm_weight: False
```

# Test Reproduction
### I provide a full replication script over [here in this gist](https://gist.github.com/152334H/5adc4fe0c20cda753d54f629be41e8c3).

But the short summary of it is that I,
* init distributed state with torch.distributed and apex.parallel_state
* define a TransformerLayer roughly equivalent to a Llama-7B layer
* create an optimizer for the transformer. I test standard torch.optim.Adam (over DDP), nn.parallel.ZeroRedundencyOptimizer (outdated ZeRO-1 equivalent), and DistributedFusedAdam (ZeRO-2 equivalent from apex). All 3 of them exhibit this issue.
* create random [seqlen, batchsize, hiddendim] sized input and output (grad) tensors
* check the equivalency of some weights before-and-after a `(fwdbck, optim.step)`

# example output (bad)
```bash
$ torchrun --nproc_per_node 2 replication.py --optim DFA
[2023-09-22 09:26:24,105] torch.distributed.run: [WARNING] 
[2023-09-22 09:26:24,105] torch.distributed.run: [WARNING] *****************************************
[2023-09-22 09:26:24,105] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2023-09-22 09:26:24,105] torch.distributed.run: [WARNING] *****************************************
/home/user/TransformerEngine/transformer_engine/pytorch/transformer.py:243: DeprecationWarning: Argument :attr:`self_attn_mask_type` has been moved to the `forward` method andis deprecated. It will be fully removed in future releases.
  warnings.warn(
/home/user/TransformerEngine/transformer_engine/pytorch/transformer.py:249: DeprecationWarning: Arguments `attention_softmax_in_fp32` and `apply_query_key_layer_scaling`are deprecated and will be fully removed in future releases.
  warnings.warn(
/home/user/TransformerEngine/transformer_engine/pytorch/module/base.py:656: UserWarning: To guarantee overlapping TP and SP collectives with the backwardGEMMs, set environment variable CUDA_DEVICE_MAX_CONNECTIONS = 1
  warnings.warn(
/home/user/TransformerEngine/transformer_engine/pytorch/transformer.py:243: DeprecationWarning: Argument :attr:`self_attn_mask_type` has been moved to the `forward` method andis deprecated. It will be fully removed in future releases.
  warnings.warn(
/home/user/TransformerEngine/transformer_engine/pytorch/transformer.py:249: DeprecationWarning: Arguments `attention_softmax_in_fp32` and `apply_query_key_layer_scaling`are deprecated and will be fully removed in future releases.
  warnings.warn(
/home/user/TransformerEngine/transformer_engine/pytorch/module/base.py:656: UserWarning: To guarantee overlapping TP and SP collectives with the backwardGEMMs, set environment variable CUDA_DEVICE_MAX_CONNECTIONS = 1
  warnings.warn(
attn_qkv weight: False
attn_ln weight: True
mlp_ln weight: True
/home/user/TransformerEngine/transformer_engine/pytorch/attention.py:104: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  data_ptr = grad_outputs[0].storage().data_ptr()
/home/user/TransformerEngine/transformer_engine/pytorch/attention.py:104: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  data_ptr = grad_outputs[0].storage().data_ptr()
attn_qkv weight: False
attn_ln weight: False
mlp_ln weight: False
```


# Package Versions
NVIDIA/TransformerEngine: c32a62ccb0a38d14d98e8bd6a14ace2d73bbac25 (current `main` commit ID, installed as pip install -e)
torch==2.2.0.dev20230914+cu121
apex: see [here](https://github.com/152334H/apex), which is identical to NVIDIA/apex `main` except with CLI flags edited to enable/compile DistributedFusedAdam. **You can use NVIDIA's main apex if you are not testing DistributedFusedAdam**.

**Comment by 152334H** [comment]
if any additional information is required please let me know

additionally, if there is a more correct way to initialize the optimizers or parallel state, i would be exceedingly grateful to be told as much

**Comment by 152334H** [comment]
nvm i'm dumb

the inputs weren't the same

after fixing that, things work as anticiated

closing this
