### ISSUE TITLE
Recomputation makes flash-attn backward slow

### ISSUE THREAD

**Issue by rejoicesyc** [NVIDIA/TransformerEngine#448]
Hi, it seems that an entire recomputation of flash-attn makes the backward stage quite slow while `checkpoint_core_attention` is triggered. The overhead can be several `contiguous` ops and a `flash_attn_fwd` op. 

One potential scenario arises when training with Megatron-LM and enabling the `--recompute-activation` flag. This overhead of the `transformer_engine` impl becomes evident since Megatron-LM doesn't use checkpoint for flash-attn.

**Comment by ptrendx** [comment]
@ksivaman What is your opinion on this? From the description it is hard to say whether the problem is on the TE side or the integration into MLM.

**Comment by rejoicesyc** [comment]
Thanks for your attention. Since MLM never uses recomputation for flash-attn, will it also be nice to make the change for TE?
