### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by foreverpiano** [NVIDIA/TransformerEngine#553]
RuntimeError:
      The detected CUDA version (12.2) mismatches the version that was used to compile
      PyTorch (11.7). Please make sure to use the same CUDA versions.

**Comment by ptrendx** [comment]
Please make sure that you install the same CUDA version as the one used by pyTorch:
 - upgrade your pyTorch version to use the newer CUDA version, the current version of pyTorch installable via pip was compiled against CUDA 12.1 (https://pytorch.org/get-started/locally/). CUDA 11.7 is unfortunately not supported by TE.
 - please install the same CUDA Toolkit version as the one used by pyTorch.
 - After that you should be able to install Transformer Engine successfully.

Alternatively, you may want to check the NGC pyTorch containers (https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) which contain the latest versions of both pyTorch and CUDA and also include Transformer Engine.
