### ISSUE TITLE
MMLU evaluation crashed with FP8 model

### ISSUE THREAD

**Issue by jingjie01ai** [NVIDIA/TransformerEngine#564]
We converted the ckpt trained by fp8 to huggingface model, and did some mmlu benchmark (bf16), found that the result was really bad but the loss is normal (compared with bf16). This issue is met after about 400B tokens training.
We tried to continue train steps with bf16 precision (**critical loss spike** at first few steps), and solved the problem of benchmark crash.  But it is not a good way to benchmark models as we need more GPUs to train the bf16 model.

Can the TE team provide any tools or practices to help benchmark the ckpt saved by fp8 training?

**Comment by ptrendx** [comment]
Hi @jingjie01ai, could you confirm that I understand your issue correctly:
 - You trained a model in FP8 for 400B tokens <- could you share the framework you used for that (NeMo, Megatron-LM, HF Accelerate etc.)?
 - Took the checkpoint, converted to BF16 and did mmlu benchmark in BF16 <- this gave bad results, even though the loss curve during training was large
 - You took the BF16 converted checkpoint and trained a bit with that
 - loss spike happened at the beginning but then it recovered and this recovered the results on MMLU benchmark <- how long did you have to train in BF16 for that?


The fact that you see the spike in the loss after converting from FP8 to BF16 is very unexpected - BF16 should be able to pretty much perfectly emulate the FP8 behavior. This suggests that the conversion from FP8 checkpoint to the BF16 checkpoint was not correct somehow.
Did the BF16 part of the training was done with the HF checkpoint or did you do that with the same codebase (just without turning FP8) as the original FP8 training? If the former - could you try loading the FP8 checkpoint into TE but with the fp8_autocast turned off and see if you see the same loss spike?
