### ISSUE TITLE
Assert error in JAX layernorm_bwd when using dtype=jnp.bfloat16

### ISSUE THREAD

**Issue by crclark** [NVIDIA/TransformerEngine#569]
[This line](https://github.com/NVIDIA/TransformerEngine/blob/efd4b62a0c3b32672e48db26736a8fd1ae07a8cd/transformer_engine/jax/flax/transformer.py#L467) suggests using `dtype=bfloat16` in the `TransformerLayer` constructor to enable fused attention, but doing so results in [this assert](https://github.com/NVIDIA/TransformerEngine/blob/efd4b62a0c3b32672e48db26736a8fd1ae07a8cd/transformer_engine/jax/cpp_extensions.py#L460) failing: 

```
File "/usr/local/lib/python3.10/dist-packages/transformer_engine/jax/layernorm.py", line 244, in _layernorm_fp8_dot_bwd_rule
    dx, dgamma, dbeta = layernorm_bwd(dgrad,
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/jax/cpp_extensions.py", line 583, in layernorm_bwd
    return LayerNormBwdPrimitive.outer_primitive.bind(dz,
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/jax/cpp_extensions.py", line 454, in abstract
    assert dtypes.canonicalize_dtype(dz_aval.dtype) == w_dtype
```

because `dtypes.canonicalize_dtype(dz_aval.dtype)` is `float32` but `w_dtype` is `bfloat16`.

**Comment by ptrendx** [comment]
@denera @nouiz Could you take a look a tthis?

**Comment by zlsh80826** [comment]
@crclark could you give a reproduce code? It seems you are trying to use the float32 dgrad and bfloat16 weight, we suggest you use bfloat16 dgrad if your forward dtype is bfloat16

**Comment by crclark** [comment]
This was a bug in my code. I didn't understand that some of the layers inside `TransformerLayer` would be implicitly coerced to `float32` even if `dtype=bfloat16` was passed into the constructor if the input to the layer was mistakenly converted to `float32`.

I.e., I'd done this

```python
layer = TransformerLayer(dtype=jnp.bfloat16)
x = some_float32_thing()
x = layer(x) # crashes
