### ISSUE TITLE
[Feature Request] Add Alibi TE supports through FA

### ISSUE THREAD

**Issue by yaoyu-33** [NVIDIA/TransformerEngine#584]
TE supports alibi through FusedAttention which is using cuDNN attention. This can be added since Flash-attn now support bias - 
https://github.com/NVIDIA/TransformerEngine/issues/369
https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/transformer.py#L571

**Comment by cyanguwa** [comment]
Please see #608.

**Comment by cyanguwa** [comment]
ALiBi and ALiBi slopes support has been added to TE.
