### ISSUE TITLE
is fwd_scale_inverses needed for bwd?

### ISSUE THREAD

**Issue by ronzillia** [NVIDIA/TransformerEngine#591]
https://github.com/NVIDIA/TransformerEngine/blob/1bb8b6ebae1ecadd7d817d572245ce5243166d32/transformer_engine/pytorch/module/layernorm_mlp.py#L499
`fwd_scale_inverses` are saved for bwd. Is there any reason for this? 
I am working on a customized fp8 layer. do I need to save `fwd_scale_inverses` for bwd or I can obtain them from `ctx.fp8_meta`?
I tried to print these values in a toy example and they look exactly the same.

**Comment by ksivaman** [comment]
The `fwd_scale_inverses` arg stores the scale inverses of the GEMM inputs and weights. If you look at the `ctx.save_for_backward` call in the forward, we clone the scale inverses and store them for the backward pass. This is needed to ensure that the backward pass sees numerically identical scale inverses for the same tensor being used in the forward. For example, in use cases such as interleaved pipeline parallelism, the forward and backward of the same module are scheduled non-trivially, and thus it is possible for the scale inverse to get updated in the following iteration before the backward is ever executed with the previous `scale_inv` value. To not make any assumptions about scheduling and be conservative, we clone the value and save it for backward. In most simple use cases (likely in your toy script), these values would be identical. Hope that makes it clear!

**Comment by ronzillia** [comment]
Hi @ksivaman ! thanks a lot for the answer. I have one more relevant question: The current implementation in TE uses a fused kernel to generate fp8 tensors of both weight/weight.T and saves them for bwd. It saves 1 cast operation but consumes extra memory. I want to cast weight.T separately in bwd with tex.cast_to_fp8. Since tex.cast_to_fp8 will override fp8_meta["scaling_fwd"].amax_history, I wonder whether it's safe to call it in bwd pass.

**Comment by ksivaman** [comment]
@ronzillia The cast from higher precision to FP8 would have to happen during the forward pass since the FP8 values are required for the GEMM. However, you can decouple the cast + transpose to just do a cast in the forward and a transpose on the backward side using `tex.fp8_transpose`, which does not require any update to amax history.
