### ISSUE TITLE
The version v1.2 has compatibility issues with PyTorch 2.0.1, causing errors during execution.

### ISSUE THREAD

**Issue by jindajia** [NVIDIA/TransformerEngine#601]
Hello,

I encountered the following error while using version v1.2 of Transformer Engine: 

`no_torch_dynamo = lambda recursive=True: lambda f: torch._dynamo.disable(f, recursive=recursive). The error message is TypeError: disable() got an unexpected keyword argument 'recursive'.
`

My environment setup is as follows: CUDA 11.8, PyTorch 2.0.1, and Python 3.10. I am experiencing this issue specifically in the context of using MegatronLM at commit fab0bd6 for Large Language Model (LLM) training. The error occurs right at the start of the training.

Possible cause of the issue:
The `disable` function in PyTorch 2.0.1 is defined as `def disable(f)`, and the recursive parameter was introduced only in later versions starting from PyTorch 2.1.0.

**Comment by ptrendx** [comment]
Thank you @jindajia for reporting this issue. I will work on a solution to this issue. In the meantime you can work around it by reverting commit https://github.com/NVIDIA/TransformerEngine/commit/7e7f09207a0b05c6e262075386d02e1743dff6c7

**Comment by ptrendx** [comment]
@jindajia and @anhdungitvn - could you test PR #627 to see if it fixes your issue? Thank you!

**Comment by jindajia** [comment]
Thank you for your repair!! I will let you know if anything happens.
