### ISSUE TITLE
 ImportError: Undefined symbol in libtransformer_engine.so when importing transformer_engine

### ISSUE THREAD

**Issue by uygnef** [NVIDIA/TransformerEngine#611]
After successfully installing the `transformer_engine` package via pip, attempting to import the `transformer_engine` module in Python results in an `OSError` due to an undefined symbol in `libtransformer_engine.so`. 
The error message is as follows:
```
>>> import transformer_engine as te
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.local/lib/python3.9/site-packages/transformer_engine/__init__.py", line 6, in <module>
    from . import common
  File "/home/.local/lib/python3.9/site-packages/transformer_engine/common/__init__.py", line 62, in <module>
    _TE_LIB_CTYPES = _load_library()
  File "/home/.local/lib/python3.9/site-packages/transformer_engine/common/__init__.py", line 38, in _load_library
    return ctypes.CDLL(dll_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/.local/lib/python3.9/site-packages/libtransformer_engine.so: undefined symbol: _ZNKSt10filesystem4path12has_filenameEv
```
Environment:
- Python version: 3.9
- GCC version: g++ 10
- C++ standard: C++17

It would be helpful if anyone could provide some insight into this issue and any potential solutions or workarounds.

Thank you for your assistance.

**Comment by ptrendx** [comment]
What is the OS you are trying it on? When looking for a potential solutions I stumbled upon this SO answer for Ubuntu 18.04: https://stackoverflow.com/a/64533485

**Comment by uygnef** [comment]
> What is the OS you are trying it on? When looking for a potential solutions I stumbled upon this SO answer for Ubuntu 18.04: https://stackoverflow.com/a/64533485

Thank you. I reinstalled GCC and set -std=c++17 in setup.py, which solved the problem.

**Comment by wowfingerlicker** [comment]
@uygnef hi, I met the same issue, which GCC version did you reinstalled and how to set -std=c++17?  thanks.

**Comment by uygnef** [comment]
> @uygnef hi, I met the same issue, which GCC version did you reinstalled and how to set -std=c++17? thanks.

I use GCC 10

**Comment by 980202006** [comment]
> @uygnef hi, I met the same issue, which GCC version did you reinstalled and how to set -std=c++17? thanks.

@wowfingerlicker I met same issue.How did you modify the setup file and reinstall?
