### ISSUE TITLE
Communication Computation Overlap issue with TransformerEngine + FSDP

### ISSUE THREAD

**Issue by denizokt** [NVIDIA/TransformerEngine#620]
I am training a large multi-node transformer model with Pytorch FSDP, and am running into some issues while using TransformerEngine. I'm not sure if this is a Pytorch issue or a TransformerEngine issue, but any advice would be very appreciated. I have also cross-posted on PyTorch (https://github.com/pytorch/pytorch/issues/117897)!

While using FSDP and TransformerEngine, I noticed that the communication/computation overlap is very poor. Looking at the traces, it seems that the TransformerEngine LayerNorm is actually waiting for the FSDP allGather in the forward pass:
<img width="916" alt="298234994-ffc5bc5c-0661-460f-96e0-b30d40380bea" src="https://github.com/NVIDIA/TransformerEngine/assets/1954448/b6a304c1-ff98-464a-a4a8-7b20c5c76ff8">

If I use custom torch linear and layernorm layers, the overlap is much better:
<img width="518" alt="298235429-28df6b02-8278-4803-ad28-59f448a26329" src="https://github.com/NVIDIA/TransformerEngine/assets/1954448/9ff084c7-7eb4-4f58-a453-f0dda0a1a6e2">

In terms of iteration time too, the torch linear + layernorm significantly outperforms the TransformerEngine layer. When the computation per FSDP group increases (say, if I bundle multiple layers into a single FSDP unit) this problem gets a lot worse.

Thank you very much for your time!

**Comment by denizokt** [comment]
Some more information on this.

The flow events suggest that the FSDP allGather is just waiting due to rate limiting, which is fine and I assume is intended behavior. The weirdness comes from the fact that the LayerNorm from two layers ago is waiting for the allGather for the current layer to finish.
<img width="478" alt="298238937-6b2dcf34-c6a0-458d-a0ed-a65d72ab28ad" src="https://github.com/NVIDIA/TransformerEngine/assets/1954448/ab75c497-48a4-43d9-b8fc-a6eeba5112b7">

**Comment by denizokt** [comment]
Okay so from the Pytorch thread (https://github.com/pytorch/pytorch/issues/117897) I learned that this is because LayerNorm is being launched as a cooperative kernel, which requires full SM occupancy. Is there a way to have the LayerNorm not require full occupancy so we can do communication/computation overlap?

If not, I can use standard Pytorch LayerNorm, but would this hurt speed when doing fused fp8?

**Comment by ptrendx** [comment]
You will want to experiment with the environment variables we introduced for this kernel to limit the number of SMs that it uses (see https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/module/layernorm.py#L150-L151). E.g. our MLPerf submission uses the values of 8 for both of them (see https://github.com/mlcommons/training_results_v3.1/blob/main/NVIDIA/benchmarks/gpt3/implementations/pytorch/config_common.sh#L10-L11), although that is for overlap with pipeline parallelism so it is possible you would need to tweak those values for FSDP.

**Comment by denizokt** [comment]
Thank you very much! For the record in our case for FSDP, 32 ended up working well.
