### ISSUE TITLE
An issue in Falcon architecture 

### ISSUE THREAD

**Issue by yongyanrao** [NVIDIA/TransformerEngine#625]
Hi team,

We noticed an issue in the Falcon architecture implementation, please let us know if we have any misunderstanding.

In HF's Falcon implementation, https://github.com/huggingface/transformers/blob/main/src/transformers/models/falcon/modeling_falcon.py, if we look at the `forward` method of `FalconDecoderLayer`, we notice that when `new_decoder_architecture=False` and `parallel_attn=True`, the workflow of the `forward` method becomes
```
residual = hidden_states
attention_layernorm_out = self.input_layernorm(hidden_states)
attn_outputs = self.self_attention(attention_layernorm_out, ...)
...
mlp_layernorm_out = attention_layernorm_out
...
mlp_output = self.mlp(mlp_layernorm_out)
...
```
So, in this case, the attention layer and the mlp layer are essentially sharing the same layernorm layer. But TE currently always assumes independent normalizations. Please let us know if we are understanding correctly.

**Comment by ptrendx** [comment]
You are right - the TE's implementation follows the `new_decoder_architecture` from HF Falcon with separate LayerNorms before attention and MLP.

That said, you should be able to emulate the single LayerNorm by sharing the parameters between the 2 LayerNorms.
