### ISSUE TITLE
TypeError: expected string or bytes-like object when building TransfromerEngine

### ISSUE THREAD

**Issue by windprak** [NVIDIA/TransformerEngine#663]
File "conda/envs/nemo/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/version.py", line 196, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object

Following line:
TransformerEngine/setup.py
Line 613 version=te_version()  had to be changed to:  version=str(te_version())

That did cost me a lot of time actually, because it was throwing a CUDA runtime not found before that.

**Comment by ptrendx** [comment]
Hmmm, to be honest I don't quite see how this function could return something other than string. Could you check what was the original type (and value) of `te_version()`?
