### ISSUE TITLE
Unable to resize Float8Tensor, Corrupted GPU memory.

### ISSUE THREAD

**Issue by jomayeri** [NVIDIA/TransformerEngine#669]
After I create a Float8Tensor I want to resize it, but attempting to do so causes a corruption of GPU memory.

Example Code:
```python
import torch
import transformer_engine.pytorch as te
hidden_size = 16384
with te.fp8_model_init(enabled=True):
    model = te.Linear(hidden_size, hidden_size, params_dtype=torch.bfloat16, bias=False)

for p in model.parameters();
   p.data = torch.empty(1).to(device=p.device, dtype=p.dtype, memory_format=torch.contiguous_format)
   print(p)
```
This results in the error:
![image](https://github.com/NVIDIA/TransformerEngine/assets/114769929/59757b49-a659-4af5-b551-3b6aa0a00a03)

I've traced the issue to the `cast_to_fp8_noalloc` kernel in the dispatch [here](https://github.com/NVIDIA/TransformerEngine/blob/da30634a6c9ccdbb6c587b6c93b1860e4b038204/transformer_engine/pytorch/float8_tensor.py#L614C1-L614C41).

1) Reviewing the code it's clear TE won't let the tensor be resized as it expands any incoming tensor to the dst tensor size. Why?
2) The operation shouldn't result in corrupted memory either way.

**Comment by ptrendx** [comment]
@jomayeri Could you give more details on why do you need to resize the Float8Tensor?

@timmoon10 FYI, any suggestions for this issue?

**Comment by jomayeri** [comment]
I want to enable DeepSpeed to work with the Float8Tensor. In DS Zero Optimizers we move the parameter data off the GPU, flatten it, then return it to the GPU [here](https://github.com/microsoft/DeepSpeed/blob/39f6ee59769fd5b1d9bfc4a3daedd63195ee73f6/deepspeed/runtime/zero/stage_1_and_2.py#L327) and [here](https://github.com/microsoft/DeepSpeed/blob/39f6ee59769fd5b1d9bfc4a3daedd63195ee73f6/deepspeed/runtime/zero/stage_1_and_2.py#L631).

**Comment by timmoon10** [comment]
In-place operations on `Float8Tensor` can become rather tricky, mostly from handling FP8 scaling factors and amaxes. One approach could be to modify the logic for `Float8Tensor.data` so that `p.data = torch.empty(1)` does the expected thing. However, we'll probably want to change it to `torch.empty(0)` or `torch.zeros(1)` so that it doesn't affect the amax:
```python
for p in model.parameters();
    p.data = torch.empty(0)
```
We could alternatively include TE-specific logic in DS:
```python
for p in model.parameters();
    if isinstance(p, Float8Tensor):
        p._data = None
    else:
        p.data = torch.empty(1)
```
