### ISSUE TITLE
Version constraint of `flash-attn` needs to be updated

### ISSUE THREAD

**Issue by lucifer1004** [NVIDIA/TransformerEngine#689]
Version: latest stable

Currently, the version constraint for `flash-attn` is:

https://github.com/NVIDIA/TransformerEngine/blob/b8eea8aaa94bb566c3a12384eda064bda8ac4fd7/setup.py#L269

So most likely `v2.4.2` is going to be installed. However, this version seems to have some issues when imported, claiming some missing symbols. I uninstalled it and manually installed the latest `v2.5.5`, and the import succeeded.

The question is: why do we set this upper bound for `flash-attn`?

**Comment by ianporada** [comment]
Is it possible to look into updating max to flash-attn version [v2.6.3](https://github.com/Dao-AILab/flash-attention/releases/tag/v2.6.3)? The compile time of this version is much faster for me than the current max v2.5.8.
