### ISSUE TITLE
Best out of the box framework for training a BitNet model

### ISSUE THREAD

**Issue by RonanKMcGovern** [NVIDIA/TransformerEngine#723]
I'm interested in pre-training a 7B model that is in either 1 or 1.58 bits.

I see that Deepspeed, HF accelerate and others are recommended. Would you have a suggestion for out of the box pre-training on 24 GPUs?

It won't be fully out of the box - because the bitlinear needs to replace the linear layers - but I'd appreciate a suggestion on what might make sense.

**Comment by timmoon10** [comment]
Paraphrasing our March 18 conversation for posterity.

I think the most straightforward approach would be to train a model in the usual FP32 precision (or FP16 with the optimizer in https://arxiv.org/pdf/2310.18313.pdf) and aggressively quantize afterwards. The challenge with training directly on quantized weights is that the optimizer can’t make fine adjustments and the convergence tends to be poor. Also, custom quantization schemes won't benefit from hardware the way FP8 training benefits from Tensor Cores.

I’m mostly familiar with pretraining, so I may be less helpful if you are thinking of other workloads. If you are using an online quantization scheme, a lot will depend on the specifics of the quantization and the required optimizer state. Perhaps you could wrap the params within your quantization scheme and cast them to/from FP8/BF16 as needed (see [`Float8Tensor`](https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/float8_tensor.py), which holds FP8 data but casts to BF16 whenever passed into PyTorch operations). This would to easier to integrate into standard PyTorch training workflows, but the extra cast kernels would hurt performance (especially if your model is small and unable to saturate the compute). LoRA might be an alternative to full-model finetuning: heavily quantize the pretrained model and do standard FP32/BF16 training on the LoRA weights.
