### ISSUE TITLE
[ERROR] cannot install the package, 

### ISSUE THREAD

**Issue by xju2** [NVIDIA/TransformerEngine#803]
The CMAKE configuration failed with the following error. The same error is observed in both *stable* and *main* branch.

```text
      -- JAX support: OFF
      -- Configuring done
      CMake Error at common/CMakeLists.txt:39 (add_library):
        Target "transformer_engine" links to target "CUDA::cublas" but the target
        was not found.  Perhaps a find_package() call is missing for an IMPORTED
        target, or an ALIAS target is missing?
```

The `CUDA::cublas` is installed throught `pip`, specifically `nvidia-cublas-cu12==12.1.3.1`.

**Comment by ptrendx** [comment]
@ksivaman Could you take a look?

**Comment by timmoon10** [comment]
It's odd that it didn't fail when it searches for cuBLAS: https://github.com/NVIDIA/TransformerEngine/blob/115a27ef2b7d206f8fc6634cfdec692913578ffc/transformer_engine/CMakeLists.txt#L22
Also, the cuBLAS pip wheel is intended for runtime use and doesn't include developer tools (https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#pip-wheels). Building TE requires the CUDA Toolkit, which includes cuBLAS.

**Comment by ksivaman** [comment]
@xju2 Adding to Tim's comment, are you building on a cuda compatible device with the toolkit installed? If so, could you try building without installing `nvidia-cublas-cu12==12.1.3.1` via pip, this should not be required.

**Comment by xju2** [comment]
It turns out to be an issue with the old cmake version. It failed with cmake 3.20.4 but worked with cmake 3.24.3. It is probably a good time to update the cmake requirement, https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/CMakeLists.txt.
