### ISSUE TITLE
`warnings.simplefilter('default')` in global scope causes excessive DeprecationWarnings

### ISSUE THREAD

**Issue by jckhan** [NVIDIA/TransformerEngine#812]
https://github.com/NVIDIA/TransformerEngine/blob/f85553ea369da15fd726ab279818e415be48a228/transformer_engine/common/utils.py#L9

Importing the `transformer_engine.common.utils` resets the warning filters to default settings using `warnings.simplefilter('default')` in the global scope. This results in the console being flooded with DeprecationWarnings, which are normally ignored by Python by default.

Would it be possible to move setting the warning filter config to a more controlled scope in this module?

**Comment by ksivaman** [comment]
@jckhan Could you confirm if #813 resolves this? Thanks!

**Comment by jckhan** [comment]
@ksivaman yes I think that works, thank you!

**Comment by timmoon10** [comment]
What kind of warnings are being reported? I'd like to make sure we're not suppressing anything important.

**Comment by jckhan** [comment]
DeprecationWarnings, ResourceWarnings, among others. The point here is that these warnings have default handling behavior defined by `warnings` https://docs.python.org/3/library/warnings.html#warning-categories, which is being overrode silently by importing `transformer_engine`. The fix suggested above is just restoring the default behavior of `warnings` globally, not suppressing any warnings that weren't being suppressed in the first place.
