### ISSUE TITLE
Can TE optimize the find cudnn?

### ISSUE THREAD

**Issue by MARD1NO** [NVIDIA/TransformerEngine#823]
Maybe user do not install cuda/cudnn toolkit independently, but pytorch will pack their own cudnn in installation package. 

I think TE can set the default cudnn path by pytorch install dir, otherwise user need to specify the cudnn include directory by setting ENV_VAR `CUDNN_INCLUDE_DIR`.

**Comment by cyanguwa** [comment]
Hi @MARD1NO, could you please give #831 a try? Thanks!
