### ISSUE TITLE
Ubuntu session close during building wheel step

### ISSUE THREAD

**Issue by Ciclarion** [NVIDIA/TransformerEngine#873]
Hello,

My system : 
Ubuntu 24.04
Cuda 12.1
CuDNN 8.9.2
Python 3.10

I've quite a strange problem. When i'm trying to install TransformerEngine with pip install git+https://github.com/NVIDIA/TransformerEngine.git@stable, my computer "crash" during the build_wheel step as my ubuntu session automatically close !

I also tried building from source, and it has the same behavior during the running setup.py 

As it crashes, i've no error message so no idea what could be the problem....

**Comment by ptrendx** [comment]
Most probably you encounter OoM error. Could you try changing `threads` value in this line: https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/CMakeLists.txt#L17 from 4 to 1? It should take longer but use less memory.

**Comment by Ciclarion** [comment]
I tried to change, but still the same problem. However as i was monitoring the gpu usage with nvidia-smi; it didn't seems to grow at all during the building. (For information, I have one rtx3090). I'll try to see what else i can change.

**Comment by Ciclarion** [comment]
It was effectively an OOM error, and i had to change the MAX_NUM_WORK env for ninja build  !
