### ISSUE TITLE
Passing context_fn to torch.utils.checkpoint results in errors when using torch.compile

### ISSUE THREAD

**Issue by MaciejBalaNV** [NVIDIA/TransformerEngine#890]
In [transformer_engine.pytorch.distributed.checkpoint](https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/distributed.py#L619) TE passes `context_fn` to `torch.utils.checkpoint.checkpoint` even if no `context_fn` was passed by the user to original function, in which case `noop_context_fn` is used. It's breaking when we are using `torch.compile`, for two reasons:

1. PyTorch is wrapping `context_fn` in `LazyVariableTracker`, which results in the error thrown [here](https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/variables/higher_order_ops.py#L1381), as `LazyVariableTracker` is not checked for in the `if` chain.
2. Even if we modify Pytorch to check for `LazyVariableTracker` e.g. by adding to the `if` chain 

```
            elif isinstance(ctx, torch._dynamo.variables.LazyVariableTracker) and ctx.value == noop_context_fn:
                context_fn = noop_context_fn
```
the error is still thrown [here](https://github.com/pytorch/pytorch/blob/main/torch/_higher_order_ops/wrap.py#L151), as PyTorch only allows `context_fn` in combination with `torch.compile` to be passed when using `_experimental_support_context_fn_in_torch_utils_checkpoint` config.

Seems like the best option, which doesn't require modifying PyTorch and using experimental config, is to simply not pass `context_fn` to `torch.utils.checkpoint.checkpoint` when `context_fn` is not specified by the user. I confirmed that this solution works with `torch.compile` without an issue.

**Comment by ptrendx** [comment]
@denera Could you look into this?

Also FYI @ptrblck.

**Comment by MaciejBalaNV** [comment]
Hey @denera, thanks a lot for looking into it. It's useful to know that other context managers also have issues with `torch.compile` combined with `te.checkpoint`. 

I just wanted to clarify one thing - there is a difference between passing `context_fn=noop_context_fn` and not passing `context_fn` at all. This difference comes from the fact that `context_fn` is not part of `kwargs` in [this](https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/variables/higher_order_ops.py#L1371) check, which means that no context manager is used at all.

**Comment by denera** [comment]
@MaciejBalaNV It looks like the line you linked is checking for *both* `'context_fn' in kwargs` and `kwargs['context_fn']=noop_context_fn`, so passing in `context_fn=noop_context_fn` here should be exactly equivalent to not passing a context function at all. Am I misunderstanding something there?

**Comment by MaciejBalaNV** [comment]
The thing is that kwargs can be wrapped in VariableTrackers when using `torch.compile`. For example that's why we have this check in PyTorch:
```
            if isinstance(ctx, torch._dynamo.variables.UserFunctionVariable):
                context_fn = ctx.fn
```
In my experiments, the `context_fn` was wrapped as `LazyVariableTracker`. It means that `kwargs['context_fn']` wasn't equal to `noop_context_fn`.
