### ISSUE TITLE
TransformerEngine setup.py fails with Python 3.8

### ISSUE THREAD

**Issue by skydoorkai** [NVIDIA/TransformerEngine#958]
This is due to /build_tools/utils.py:
from functools import cache

which is not a Python 3.8 feature.

#CUDACXX=/usr/local/cuda/bin/nvcc NVTE_FRAMEWORK=pytorch python setup.py bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    from build_tools.build_ext import CMakeExtension, get_build_ext
  File "/w/github/TransformerEngine/build_tools/build_ext.py", line 20, in <module>
    from .utils import (
  File "/w/github/TransformerEngine/build_tools/utils.py", line 13, in <module>
    from functools import cache
ImportError: cannot import name 'cache' from 'functools' (/opt/conda/lib/python3.8/functools.py)

**Comment by timmoon10** [comment]
Thanks for the catch, can you try with https://github.com/NVIDIA/TransformerEngine/pull/967?

**Comment by skydoorkai** [comment]
> Thanks for the catch, can you try with #967?

This works for 3.8.
